name: Multiarch builds

on: push

jobs:
  build-image:
    name: Build image
    uses: openshift-knative/hack/.github/workflows/multiarch-containerfile-build.yaml@main
    secrets: inherit
    strategy:
      matrix:
        image:
        - test/eventshub
        - test/wathola-forwarder
    with:
      image: ${{ matrix.image }}
      containerfile: .github/workflows/images/${{ matrix.image }}/Containerfile
